var inquirer = require("inquirer");
var fs = require("fs");
var axios = require("axios");

// const questions = [
//     'Title',
//     'Description',
//     'Table of Contents',
//     'Installation',
//     'Usage',
//     'License',
//     'Contributing',
//     'Tests',
//     'Questions'
// ];



function init() {
    inquirer
        .prompt([
            {
                type: "input",
                message: "What is your Github username?",
                name: "github"
            },
            {
                type: "input",
                message: "What is the title of this repo?",
                name: "title"
            },
            {
                type: "input",
                message: "What is a good description for this repo?",
                name: "description"
            },
            {
                type: "input",
                message: "Describe the installation process.",
                name: "installation"
            },
            {
                type: "input",
                message: "How does someone use this repo?",
                name: "usage"
            },
            {
                type: "list",
                message: "What license is being used?",
                name: "license",
                choices: [
                    "MIT",
                    "GPLv3",
                    "AGPL",
                    "None"
                ]
            },
            {
                type: "input",
                message: "Who are the contributors (seperated by cammas without spaces)?",
                name: "contributors"
            },
            {
                type: "input",
                message: "How does the user run tests?",
                name: "tests"
            }
        ])
        .then(function(data) {
            const queryUrl = `https://api.github.com/users/${data.github}/events/public`;

            axios.get(queryUrl)
                .then(function(response) {
                    data.email = response.data[0].payload.commits[0].author.email;
                    data.avatar = response.data[0].actor.avatar_url;
                    return data
                })
                .then(function({title, description, installation, usage, license, contributors, tests, email, avatar}){

                    // var contributorsArray = contributors.split(',');

                    var inputData = `# ${title}\n## Description\n${description}\n## Table of Contents\n[Installation](#installation)<br>\n[Usage](#uage)<br>\n[License](#license)<br>\n[Contributors](#contributors)<br>\n[Testing](#testing)\n## Installation\n${installation}\n## Usage\n${usage}\n## License\n${license}\n## Contributors\n${contributors}\n## Testing\n${tests}\n## Generated By\n <br> ![alt text](${avatar}) <br> ${email}`
                    writeToFile("generated-readme.md", inputData)
                })

            
        });
    // Build the data according to the user's input
    // Call the writeToFile function
}

function writeToFile(fileName, data) {
    // write all the data to the file
    fs.writeFile(fileName, data, function(err) {

        if (err) {
          return console.log(err);
        }
      
        console.log("Success!");
      
      });
      
}

init();
