var inquirer = require("inquirer");
var fs = require("fs");
var axios = require("axios");

function init() {
    inquirer
        .prompt([
            {
                type: "input",
                message: "What is your Github username?",
                name: "github"
            },
            {
                type: "input",
                message: "What is the title of this repo?",
                name: "title"
            },
            {
                type: "input",
                message: "What is a good description for this repo?",
                name: "description"
            },
            {
                type: "input",
                message: "Describe the installation process.",
                name: "installation"
            },
            {
                type: "input",
                message: "How does someone use this repo?",
                name: "usage"
            },
            {
                type: "list",
                message: "What license is being used?",
                name: "license",
                choices: [
                    "MIT",
                    "GPLv3",
                    "AGPL",
                    "None"
                ]
            },
            {
                type: "input",
                message: "Who are the contributors (seperated by cammas without spaces)?",
                name: "contributors"
            },
            {
                type: "input",
                message: "How does the user run tests?",
                name: "tests"
            }
        ])
        .then(function(data) {
            const queryUrl = `https://api.github.com/users/${data.github}/events/public`;

            axios.get(queryUrl)
                .then(function(response) {
                    data.email = response.data[0].payload.commits[0].author.email;
                    data.avatar = response.data[0].actor.avatar_url;
                    return data
                })
                .then(function({title, description, installation, usage, license, contributors, tests, email, avatar}){

                    // Split up contributors on commas and then join then on breaks
                    var contributorsArray = contributors.split(',');
                    var contributorsText = contributorsArray.join('<br>')

                    // Check for the license
                    var licenseText;
                    if (license === 'MIT'){
                        licenseText = `[![MIT License](https://img.shields.io/apm/l/atomic-design-ui.svg?)](https://github.com/tterb/atomic-design-ui/blob/master/LICENSEs)`
                    }
                    else if (license === 'GPLv3'){
                        licenseText = `[![GPLv3 License](https://img.shields.io/badge/License-GPL%20v3-yellow.svg)](https://opensource.org/licenses/)`
                    }
                    else if (license === 'AGPL'){
                        licenseText = `[![AGPL License](https://img.shields.io/badge/license-AGPL-blue.svg)](http://www.gnu.org/licenses/agpl-3.0)`
                    }
                    else {
                        licenseText = `This project does not use any license.`
                    }

                    var inputData = `# ${title}\n## Description\n${description}\n## Table of Contents\n[Installation](#installation)<br>\n[Usage](#uage)<br>\n[License](#license)<br>\n[Contributors](#contributors)<br>\n[Testing](#testing)\n## Installation\n${installation}\n## Usage\n${usage}\n## License\n${licenseText}\n## Contributors\n${contributorsText}\n## Testing\n${tests}\n### This readme was generated by:\n <br> ![alt text](${avatar}) <br> ${email}`
                    writeToFile("generated-readme.md", inputData)
                })

            
        });
    // Build the data according to the user's input
    // Call the writeToFile function
}

function writeToFile(fileName, data) {
    // write all the data to the file
    fs.writeFile(fileName, data, function(err) {

        if (err) {
          return console.log(err);
        }
      
        console.log("Success!");
      
      });
      
}

init();
